CREATE TABLE Estaticos(
 Grupo VARCHAR(50) NOT NULL,
 Codigo VARCHAR(10) NOT NULL,
 Valor VARCHAR(50) NOT NULL,
 Orden INT NOT NULL,
 CONSTRAINT PK_Grupo PRIMARY KEY(Grupo,Codigo)
)
go
CREATE TABLE Cliente(
 Id INT IDENTITY(1,1),
 Codigo VARCHAR(50) NOT NULL,
 Nombre VARCHAR(200) NOT NULL,
 TipoDocumento INT NOT NULL,
 Documento INT NOT NULL,
 Email VARCHAR(100) NOT NULL
 CONSTRAINT PK_Id PRIMARY KEY(Id)
)
GO
CREATE TABLE Producto(
 Id INT IDENTITY(1,1),
 Codigo VARCHAR(50) NOT NULL,
 Nombre VARCHAR(200) NOT NULL,
 PrecioVenta DECIMAL(18,2) NOT NULL,
 Stock INT NOT NULL,
 CONSTRAINT PK_IdProducto PRIMARY KEY(Id)
)
GO
CREATE TABLE Usuario(
 Id INT IDENTITY(1,1),
 Nombre VARCHAR(200) NOT NULL,
 Cuenta VARCHAR(100) NOT NULL,
 Contrasena VARCHAR(100) NOT NULL,
 Estado INT NOT NULL,
 CONSTRAINT PK_IdUsuario PRIMARY KEY(Id)
)
GO
CREATE TABLE Venta(
 Id INT IDENTITY(1,1),
 IdCliente INT NOT NULL,
 IdUsuario INT NOT NULL,
 Fecha DATETIME NOT NULL,
 CONSTRAINT PK_IdVenta PRIMARY KEY(Id),
 CONSTRAINT FK_IdCliente_Cliente FOREIGN KEY(IdCliente) REFERENCES dbo.Cliente(Id),
 CONSTRAINT FK_IdUsuario_Usuario FOREIGN KEY(IdUsuario) REFERENCES dbo.Usuario(Id)
)
GO
CREATE TABLE VentaDetalle(
 IdVenta INT NOT NULL,
 IdProducto INT NOT NULL,
 Cantidad INT NOT NULL,
 PrecioUnitario DECIMAL NOT NULL,
 Descuento DECIMAL(18,2) NOT NULL,
 Subtotal DECIMAL(18,2) NOT NULL,
 CONSTRAINT PK_VentaDetalle PRIMARY KEY(IdVenta,IdProducto),
 CONSTRAINT FK_IdVenta_Venta FOREIGN KEY(IdVenta) REFERENCES dbo.Venta(Id),
 CONSTRAINT KF_IdProducto_Producto FOREIGN KEY(IdProducto) REFERENCES dbo.Producto(Id)
)
